#!/usr/bin/env python3
"""Async Comprehensions"""

import asyncio
from typing import List
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    A coroutine that collects 10 random numbers from an asynchronous generator.

    This coroutine uses an async comprehension to collect 10 random numbers
    generated by the `async_generator` coroutine.

    Returns:
        List[float]: A list of 10 random floats between 0 and 10.
    """
    results = [i async for i in async_generator()]
    return results
